version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

#  app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"

  auth:
    image: jboss/keycloak
    volumes:
      - ./keycloak/media_realm.json:/tmp/media_realm.json
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/media_realm.json
