version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

#  app:
#    build: .
#    working_dir: /app
#    volumes:
#      - ./:/app
#      - ~/.m2:/root/.m2
#    command: mvn clean spring-boot:run
#    depends_on:
#      - db
#    ports:
#      - 8081:8081

  auth:
    image: jboss/keycloak
    volumes:
      - ./keycloak/media_realm.json:/tmp/media_realm.json
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/media_realm.json

  logstash:
    image: logstash:7.1.0
    command: bash -c "logstash -f /etc/logstash/conf.d/logstash.conf && bin/logstash-plugin install logstash-input-jdbc"
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/postgresql-9.1-901-1.jdbc4.jar:/etc/logstash/conf.d/postgresql-9.1-901-1.jdbc4.jar

    depends_on:
      - db
      - elasticsearch
    ports:
      - 5959:5959

  elasticsearch:
    image: elasticsearch:5.4
    ports:
      - 9200:9200
    environment:
      cluster.name: media
