version: '3'
services:
  db:
    image: postgres
#    volumes:
#      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#      - db-data:/var/lib/postgresql/data
#      - ./postgres/dump.sql:/dump.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"