spring:
  datasource:
    url: jdbc:postgresql://db:5432/media
    username: postgres
    password: postgres

  jpa.properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl.auto: create-drop
      temp.use_jdbc_metadata_defaults: false
      show_sql: true
      use_sql_comments: true
      format_sql: true


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false