spring:
  datasource:
    url: jdbc:postgresql://db:5432/media
    username: postgres
    password: postgres

  jpa.properties:
    hibernate:
#      hbm2ddl.auto: create-drop
#      default_schema: media
      temp.use_jdbc_metadata_defaults: false
      show_sql: true
      use_sql_comments: true
      format_sql: true