server.port: 8081

spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/media
    username: postgres
    password: postgres
#    hikari:
#      leakDetectionThreshold: 10001
#      minimumIdle: 3
#      maximumPoolSize: 10
#      maxLifetime: 2000
#      connection-test-query: SELECT 1

  jpa.properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl.auto: create-drop
      temp.use_jdbc_metadata_defaults: false
      show_sql: true
      use_sql_comments: true
      format_sql: true


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

keycloak:
  realm: media_realm
  bearer-only: true
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: rest_media_client_id
  use-resource-role-mappings: true
